#!/usr/bin/env python3
"""TVmine library tool — add, update, and remove shows/movies offline.

The source of truth is library.json; every command that changes it also
regenerates data.js, which is what the website reads. Covers are downloaded
from TMDB into covers/.

Setup (once):
  1. Get a free TMDB API key: https://www.themoviedb.org/settings/api
  2. Save it:  echo "YOUR_KEY" > .tmdb_key      (or export TMDB_API_KEY=...)

Usage:
  ./tvmine.py add "Frieren" --score 9.5 --status watching --progress 1:21/28
  ./tvmine.py add "Perfect Days" --type movie --notes "rainy day pick"
  ./tvmine.py update frieren --score 10 --status watched
  ./tvmine.py update severance --progress 2:5/10
  ./tvmine.py remove the-bear-s3
  ./tvmine.py list
  ./tvmine.py regen          # just rebuild data.js from library.json

No dependencies beyond the standard library.
"""

import argparse
import datetime
import json
import re
import sys
import urllib.parse
import urllib.request
from pathlib import Path

ROOT = Path(__file__).resolve().parent
LIBRARY_PATH = ROOT / "library.json"
DATA_JS_PATH = ROOT / "data.js"
COVERS_DIR = ROOT / "covers"

TMDB_API = "https://api.themoviedb.org/3"
TMDB_IMG = "https://image.tmdb.org/t/p/w500"

DATA_JS_HEADER = """\
// GENERATED by tvmine.py from library.json — do not edit by hand.
// Edit entries with:  ./tvmine.py add|update|remove   (see ./tvmine.py --help)

const LIBRARY = """


# ---------- library file handling ----------

def load_library():
    if not LIBRARY_PATH.exists():
        return []
    return json.loads(LIBRARY_PATH.read_text(encoding="utf-8"))


def save_library(lib):
    LIBRARY_PATH.write_text(json.dumps(lib, indent=2, ensure_ascii=False) + "\n",
                            encoding="utf-8")
    DATA_JS_PATH.write_text(DATA_JS_HEADER + json.dumps(lib, indent=2, ensure_ascii=False) + ";\n",
                            encoding="utf-8")
    print(f"saved {len(lib)} entries -> library.json + data.js")
    dupes = library_duplicates(lib)
    if dupes:
        names = "; ".join(" / ".join(f"[{e['id']}]" for e in g) for g in dupes)
        print(f"warning: possible duplicates: {names}  (run ./tvmine.py check)")


def slugify(title):
    slug = re.sub(r"[^a-z0-9]+", "-", title.lower()).strip("-")
    return slug or "untitled"


def unique_slug(lib, title):
    base = slugify(title)
    slug, n = base, 2
    ids = {e["id"] for e in lib}
    while slug in ids:
        slug = f"{base}-{n}"
        n += 1
    return slug


def find_entry(lib, key):
    """Find by exact id, then by title substring."""
    for e in lib:
        if e["id"] == key:
            return e
    matches = [e for e in lib if key.lower() in e["title"].lower()]
    if len(matches) == 1:
        return matches[0]
    if len(matches) > 1:
        sys.exit("ambiguous match: " + ", ".join(e["id"] for e in matches))
    sys.exit(f"no entry matching '{key}' (try ./tvmine.py list)")


# ---------- TMDB ----------

def tmdb_key():
    import os
    key = os.environ.get("TMDB_API_KEY")
    if not key:
        keyfile = ROOT / ".tmdb_key"
        if keyfile.exists():
            key = keyfile.read_text().strip()
    if not key:
        sys.exit("no TMDB API key. Put it in .tmdb_key or export TMDB_API_KEY.\n"
                 "Get one free at https://www.themoviedb.org/settings/api")
    return key


def tmdb_get(path, **params):
    key = tmdb_key()
    headers = {"User-Agent": "tvmine/1.0"}
    if key.startswith("eyJ"):  # v4 read access token
        headers["Authorization"] = f"Bearer {key}"
    else:
        params["api_key"] = key
    url = f"{TMDB_API}{path}?{urllib.parse.urlencode(params)}"
    req = urllib.request.Request(url, headers=headers)
    with urllib.request.urlopen(req, timeout=15) as resp:
        return json.load(resp)


def search_tmdb(query, media_type=None):
    """Return a list of candidate dicts: {tmdb_id, type, title, year, overview}."""
    kind = media_type or "multi"
    data = tmdb_get(f"/search/{kind}", query=query, include_adult="false")
    out = []
    for r in data.get("results", []):
        rtype = r.get("media_type", media_type)
        if rtype not in ("movie", "tv"):
            continue
        title = r.get("title") or r.get("name") or "?"
        date = r.get("release_date") or r.get("first_air_date") or ""
        out.append({
            "tmdb_id": r["id"],
            "type": rtype,
            "title": title,
            "year": int(date[:4]) if date[:4].isdigit() else None,
            "overview": r.get("overview") or "",
            "poster_path": r.get("poster_path"),
            "popularity": r.get("popularity", 0),
        })
    return out


def pick_result(results, first=False):
    if not results:
        sys.exit("no TMDB results found.")
    if first or len(results) == 1:
        return results[0]
    print("\nmatches:")
    for i, r in enumerate(results[:8], 1):
        year = r["year"] or "????"
        blurb = (r["overview"][:70] + "…") if len(r["overview"]) > 70 else r["overview"]
        print(f"  {i}. [{r['type']:5}] {r['title']} ({year})  {blurb}")
    while True:
        choice = input("pick a number (or q to abort): ").strip()
        if choice.lower() == "q":
            sys.exit("aborted.")
        if choice.isdigit() and 1 <= int(choice) <= min(len(results), 8):
            return results[int(choice) - 1]


def fetch_details(tmdb_id, media_type):
    d = tmdb_get(f"/{media_type}/{tmdb_id}")
    genres = [g["name"] for g in d.get("genres", [])]
    # trim TMDB's sometimes-long genre names to match the site's chip style
    genres = [g.replace("Science Fiction", "Sci-Fi").replace(" & ", " / ") for g in genres]
    return d, genres


def download_cover(poster_path, slug):
    if not poster_path:
        print("no poster available on TMDB — keeping painted placeholder.")
        return None
    COVERS_DIR.mkdir(exist_ok=True)
    dest = COVERS_DIR / f"{slug}.jpg"
    req = urllib.request.Request(TMDB_IMG + poster_path,
                                 headers={"User-Agent": "tvmine/1.0"})
    with urllib.request.urlopen(req, timeout=30) as resp:
        dest.write_bytes(resp.read())
    print(f"cover -> covers/{slug}.jpg")
    return f"covers/{slug}.jpg"


# ---------- field parsing ----------

def parse_progress(text):
    """'1:21/28' -> {season 1, episode 21, episodesInSeason 28}"""
    m = re.fullmatch(r"(\d+):(\d+)/(\d+)", text.strip())
    if not m:
        sys.exit("bad --progress format, expected S:E/TOTAL e.g. 2:5/10")
    return {"season": int(m[1]), "episode": int(m[2]), "episodesInSeason": int(m[3])}


def today():
    return datetime.date.today().isoformat()


# ---------- duplicate detection ----------

def normalize_title(title):
    """Fold case/punctuation so 'Howl's Moving Castle!' == 'howls moving castle'."""
    return re.sub(r"[^a-z0-9]+", " ", title.lower()).strip()


def find_duplicates(lib, tmdb_id, title, media_type):
    """Entries that look like the same work: exact TMDB id, or same
    normalized title + type (catches entries added without a TMDB id)."""
    norm = normalize_title(title)
    dupes = []
    for e in lib:
        if tmdb_id is not None and e.get("tmdbId") == tmdb_id:
            dupes.append((e, "same TMDB id"))
        elif normalize_title(e["title"]) == norm and e["type"] == media_type:
            dupes.append((e, "same title"))
    return dupes


def confirm_duplicate(dupes, interactive):
    """Show what already matches; return True only if the user insists."""
    print("\nalready in the library:")
    for e, why in dupes:
        print(f"  [{e['id']}] {e['title']} ({e.get('year', '?')}) — {e['status']}  ({why})")
    print("to change an existing entry:  ./tvmine.py update <id> ...")
    if not interactive:
        print("refusing to add a duplicate (pass --again to override).")
        return False
    ans = input("add it anyway? [y/N]: ").strip().lower()
    return ans in ("y", "yes")


def library_duplicates(lib):
    """Scan the whole library, return groups of entries that look identical
    (matching TMDB id, or matching normalized title + type)."""
    by_tmdb, by_title = {}, {}
    for e in lib:
        if e.get("tmdbId") is not None:
            by_tmdb.setdefault(e["tmdbId"], []).append(e)
        by_title.setdefault((normalize_title(e["title"]), e["type"]), []).append(e)
    groups, reported = [], set()
    for g in list(by_tmdb.values()) + list(by_title.values()):
        ids = frozenset(e["id"] for e in g)
        if len(g) > 1 and ids not in reported:
            reported.add(ids)
            groups.append(g)
    return groups


# ---------- commands ----------

def cmd_add(args):
    lib = load_library()
    if args.status is None:
        # a score means you've seen it; otherwise it's a plan
        args.status = "watched" if args.score is not None else "towatch"
    results = search_tmdb(args.title, args.type)
    chosen = pick_result(results, first=args.first)
    dupes = find_duplicates(lib, chosen["tmdb_id"], chosen["title"], chosen["type"])
    if dupes and not args.again:
        if not confirm_duplicate(dupes, interactive=not args.first):
            sys.exit(1)
    details, genres = fetch_details(chosen["tmdb_id"], chosen["type"])
    slug = unique_slug(lib, chosen["title"])
    poster = download_cover(chosen["poster_path"], slug)

    entry = {
        "id": slug,
        "title": chosen["title"],
        "type": chosen["type"],
        "status": args.status,
        "year": chosen["year"],
        "genres": genres or ["Unknown"],
        "score": args.score,
        "synopsis": chosen["overview"],
        "date": args.date or today(),
        "poster": poster,
        "tmdbId": chosen["tmdb_id"],
    }
    if args.notes:
        entry["notes"] = args.notes
    if args.progress:
        entry["progress"] = parse_progress(args.progress)
    elif chosen["type"] == "tv" and args.status == "watching":
        eps = details.get("number_of_episodes")
        if details.get("number_of_seasons") == 1 and eps:
            entry["progress"] = {"season": 1, "episode": 0, "episodesInSeason": eps}

    lib.append(entry)
    save_library(lib)
    print(f"added: {entry['title']} ({entry['year']}) [{entry['id']}] as {entry['status']}")


def cmd_update(args):
    lib = load_library()
    e = find_entry(lib, args.id)
    if args.score is not None:
        e["score"] = args.score
        # scoring something means you've watched it (unless told otherwise)
        if not args.status and e["status"] != "watched":
            args.status = "watched"
    if args.status:
        if args.status == "watched" and e["status"] != "watched" and not args.date:
            e["date"] = today()  # finished today
        e["status"] = args.status
        if args.status != "watching":
            e.pop("progress", None)
    if args.date:
        e["date"] = args.date
    if args.notes is not None:
        if args.notes:
            e["notes"] = args.notes
        else:
            e.pop("notes", None)
    if args.progress:
        e["progress"] = parse_progress(args.progress)
    save_library(lib)
    print(f"updated: {e['title']} [{e['id']}]")


def cmd_remove(args):
    lib = load_library()
    e = find_entry(lib, args.id)
    lib.remove(e)
    cover = e.get("poster")
    if cover and (ROOT / cover).exists() and not args.keep_cover:
        (ROOT / cover).unlink()
        print(f"deleted {cover}")
    save_library(lib)
    print(f"removed: {e['title']} [{e['id']}]")


def cmd_list(args):
    lib = load_library()
    order = {"watching": 0, "towatch": 1, "watched": 2}
    for e in sorted(lib, key=lambda x: (order.get(x["status"], 9), x["title"])):
        score = f"{e['score']:>4}" if e.get("score") is not None else "  — "
        prog = ""
        if e.get("progress"):
            p = e["progress"]
            prog = f"  S{p['season']}·E{p['episode']}/{p['episodesInSeason']}"
        print(f"{e['status']:9} {score}  {e['title']} ({e.get('year','?')}) [{e['id']}]{prog}")
    print(f"\n{len(lib)} entries")


def cmd_regen(args):
    save_library(load_library())


def cmd_check(args):
    lib = load_library()
    groups = library_duplicates(lib)
    if not groups:
        print(f"no duplicates found in {len(lib)} entries.")
        return
    print(f"{len(groups)} possible duplicate group(s):\n")
    for g in groups:
        for e in g:
            print(f"  [{e['id']}] {e['title']} ({e.get('year', '?')}) "
                  f"— {e['status']}, tmdbId={e.get('tmdbId')}")
        print(f"  keep one, remove the rest:  ./tvmine.py remove <id>\n")
    sys.exit(1)


def main():
    ap = argparse.ArgumentParser(description=__doc__,
                                 formatter_class=argparse.RawDescriptionHelpFormatter)
    sub = ap.add_subparsers(dest="cmd", required=True)

    a = sub.add_parser("add", help="look up a title on TMDB and add it")
    a.add_argument("title")
    a.add_argument("--type", choices=["movie", "tv"], help="constrain the search")
    a.add_argument("--status", choices=["watching", "towatch", "watched"],
                   help="default: towatch, or watched when --score is given")
    a.add_argument("--score", type=float)
    a.add_argument("--notes")
    a.add_argument("--progress", help="S:E/TOTAL e.g. 1:21/28")
    a.add_argument("--date", help="YYYY-MM-DD (default: today)")
    a.add_argument("--first", action="store_true", help="take the top result, don't ask")
    a.add_argument("--again", action="store_true", help="allow adding a title already in the library")
    a.set_defaults(fn=cmd_add)

    u = sub.add_parser("update", help="change score/status/progress/notes of an entry")
    u.add_argument("id", help="entry id or title fragment")
    u.add_argument("--score", type=float)
    u.add_argument("--status", choices=["watching", "towatch", "watched"])
    u.add_argument("--notes", help="new notes ('' to clear)")
    u.add_argument("--progress", help="S:E/TOTAL e.g. 2:5/10")
    u.add_argument("--date", help="YYYY-MM-DD")
    u.set_defaults(fn=cmd_update)

    r = sub.add_parser("remove", help="delete an entry (and its cover)")
    r.add_argument("id", help="entry id or title fragment")
    r.add_argument("--keep-cover", action="store_true")
    r.set_defaults(fn=cmd_remove)

    sub.add_parser("list", help="print the library").set_defaults(fn=cmd_list)
    sub.add_parser("regen", help="rebuild data.js from library.json").set_defaults(fn=cmd_regen)
    sub.add_parser("check", help="scan the library for duplicate entries").set_defaults(fn=cmd_check)

    args = ap.parse_args()
    args.fn(args)


if __name__ == "__main__":
    main()
